services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: polymonitor-backend-dev
    env_file:
      - ./backend/.env.docker
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: polymonitor-frontend-dev
    env_file:
      - ./frontend/.env.docker
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
      - frontend_node_modules:/app/frontend/node_modules
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  frontend_node_modules:
